# Stage 1: Install dependencies
FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./

RUN npm install

# Stage 2: Build the application
FROM node:22-alpine AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build

RUN npm ci --omit=dev && npm cache clean --force

# Stage 3: Final production image
FROM node:22-alpine AS prod


WORKDIR /app

ARG PORT
ENV PORT=${PORT}

RUN addgroup -S lambda-group && adduser -S lambda -G lambda-group

COPY --from=build --chown=lambda:lambda-group /app/node_modules ./node_modules
COPY --from=build --chown=lambda:lambda-group /app/dist ./dist

EXPOSE ${PORT}

USER lambda

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
	CMD wget --quiet --tries=1 --spider http://localhost:${PORT}/api/v1.0 || exit 1


CMD [ "node", "dist/main.js" ]